[tool.poetry]
name = "bigferret"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
fastapi = ">=0.95.2,<0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.0"}
peewee = "^3.16.2"
langchain = {extras = ["llm"], version = "^0.0.235"}
boto3 = "^1.28.4"
chromadb = "^0.4.0"
openai = "^0.27.8"
tiktoken = "^0.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
