[tool.poetry]
name = "turbine"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pymilvus = "^2.2.15"
openai = "^0.27.8"
flask = "^2.3.2"
flask-restful = "^0.3.10"
kafka-python = "^2.0.2"
requests = "^2.31.0"
peewee = "^3.16.3"
python-dotenv = "^1.0.0"
tiktoken = "^0.4.0"
psycopg2-binary = "^2.9.7"
pymongo = "^4.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
