[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Sumit Ghosh <sumit@sumit-ghosh.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.2"
dotmap = "^1.3.30"
authlib = "^1.2.1"
requests = "^2.31.0"
google-api-python-client = "^2.93.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
python-dotenv = "^1.0.0"
peewee = "^3.16.2"

[tool.poetry.group.dev.dependencies]
google-api-python-client-stubs = "^1.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
