[tool.poetry]
name = "bigferret"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.0"}
peewee = "^3.16.2"
langchain = "^0.0.235"
boto3 = "^1.28.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
