[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Sumit Ghosh <sumit@sumit-ghosh.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"
pyyaml = "^6.0"
dotmap = "^1.3.30"
authlib = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
