version: "3"

tasks:
  docker:clean:dev:
    desc: Clean local development stack on Docker Compose.
    cmds:
      - cd docker/dev && docker compose down
  docker:clean:prod:
    desc: Clean production stack on Docker Compose.
    cmds:
      - cd docker/prod && docker compose down
  docker:run:dev:
    desc: Run local development setup using Docker Compose.
    deps:
      - docker:clean:dev
      - docker:clean:prod
    cmds:
      - cd docker/dev && docker compose up -V --remove-orphans --build
  docker:run:prod:
    desc: Run production setup using Docker Compose.
    deps:
      - docker:clean:dev
      - docker:clean:prod
    cmds:
      - cd docker/prod && docker compose up --remove-orphans --build -d
