version: "3"

services:
  api:
    build:
      context: ../..
      dockerfile: docker/dev/common.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
      - prefect
      - worker
    env_file: .env
    command: sh -c "alembic upgrade head && uvicorn turbine.api.app:app --reload --host 0.0.0.0 --port 80"
    volumes:
      - ../..:/app
    restart: always

  worker:
    build:
      context: ../..
      dockerfile: docker/dev/common.Dockerfile
    env_file: .env
    depends_on:
      - prefect
    volumes:
      - ../..:/app
    restart: always
    command: prefect agent start -p "default-agent-pool"
    deploy:
      replicas: 3

  prefect:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "4200:4200"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "api"
    depends_on:
      - api
    volumes:
      - ./ngrok.yml:/var/lib/ngrok/ngrok.yml
    ports:
      - "4040:4040"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_MULTIPLE_DATABASES: turbine, prefect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
