version: "3"

services:
  api:
    image: turbine/api
    build:
      context: ../..
      dockerfile: docker/dev/api.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
      - worker
    env_file: .env
    command: uvicorn turbine.api.app:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ../..:/app
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "api"
    depends_on:
      - api
    volumes:
      - ./ngrok.yml:/var/lib/ngrok/ngrok.yml
    ports:
      - "4040:4040"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: turbine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"

  worker:
    image: turbine/worker
    build:
      context: ../..
      dockerfile: docker/dev/worker.Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
      - redis
    command: celery --app turbine.worker.worker worker --loglevel=INFO
    volumes:
      - ../..:/app
    restart: always

  flower:
    image: turbine/flower
    build:
      context: ../..
      dockerfile: docker/dev/flower.Dockerfile
    env_file: .env
    ports:
      - "5555:5555"
    command: celery --app turbine.worker.worker flower
    volumes:
      - ../..:/app
    restart: always
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
