version: "3"

services:
  turbine-api:
    container_name: turbine-api
    image: turbine/api
    build:
      context: ../..
      dockerfile: docker/dev/turbine-api.Dockerfile
    ports:
      - "80:80"
    depends_on:
      # - milvus
      - postgres
    env_file: .env
    command: uvicorn turbine.api.app:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ../..:/turbine-api
    restart: always

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "api"
    volumes:
      - ./ngrok.yml:/var/lib/ngrok/ngrok.yml
    ports:
      - "4040:4040"

  postgres:
    image: postgres:latest
    container_name: turbine-postgres
    environment:
      POSTGRES_DB: turbine
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"

  turbine-worker:
    container_name: turbine-worker
    image: turbine/worker
    build:
      context: ../..
      dockerfile: docker/dev/turbine-worker.Dockerfile
    depends_on:
      - milvus
    env_file: .env
    command: celery --app turbine.worker.worker worker --loglevel=INFO
    volumes:
      - ../..:/turbine-worker
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
