version: "3"

services:
  turbine-api:
    container_name: turbine-api
    image: turbine/api
    build:
      context: ../..
      dockerfile: docker/prod/turbine-api.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redpanda
      - debezium
    env_file: .env

  turbine-daemon:
    container_name: turbine-daemon
    image: turbine/daemon
    build:
      context: ../..
      dockerfile: docker/prod/turbine-daemon.Dockerfile
    depends_on:
      - redpanda
      - debezium
    env_file: .env

  redpanda:
    container_name: redpanda
    image: vectorized/redpanda
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --check=false

  debezium:
    image: debezium/connect
    container_name: debezium
    depends_on:
      - redpanda
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "inventory.configs"
      OFFSET_STORAGE_TOPIC: "inventory.offset"
      STATUS_STORAGE_TOPIC: "inventory.status"
