version: "3"

services:
  api:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    ports:
      - "80:80"
    env_file: .env
    restart: always
    command: uvicorn turbine.api.app:app --host 0.0.0.0 --port 80

  worker:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    depends_on:
      - prefect
    env_file: .env
    restart: always
    deploy:
      replicas: 10
    command: prefect agent start -p "default-agent-pool"

  prefect:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    restart: always
    depends_on:
      - postgres
    env_file: .env

  nginx:
    image: nginx:alpine
    ports:
      - "4200:4200"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    restart: always
