version: "3"

services:
  api:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    ports:
      - "80:80"
    env_file: .env
    restart: always
    command: uvicorn turbine.api.app:app --host 0.0.0.0 --port 80

  worker:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    depends_on:
      - prefect
    env_file: .env
    restart: always
    deploy:
      replicas: 3
    command: prefect agent start -p "default-agent-pool"

  prefect:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    restart: always
    env_file: .env

  minio:
    image: minio/minio
    ports:
      - "9001:9001"
    env_file: .env
    command: server --console-address ":9001" /data

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    environment:
      - UNSTRUCTURED_MEMORY_FREE_MINIMUM_MB=500

  nginx:
    image: nginx:alpine
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
    depends_on:
      - api
    restart: always
