version: "3"

services:
  api:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    ports:
      - "80:80"
    env_file: .env
    restart: always
    command: uvicorn turbine.api.app:app --host 0.0.0.0 --port 80

  worker:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    depends_on:
      - rabbitmq
      - redis
    env_file: .env
    restart: always
    deploy:
      replicas: 10
    command: celery --app turbine.worker.worker worker --loglevel=INFO

  flower:
    build:
      context: ../..
      dockerfile: docker/prod/common.Dockerfile
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    env_file: .env
    command: celery --app turbine.worker.worker flower

  rabbitmq:
    image: "rabbitmq:management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: turbine
      RABBITMQ_DEFAULT_PASS: tHeOUroUStOl
    ports:
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
      - ./volumes/rabbitmq/config:/etc/rabbitmq

  redis:
    image: "redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./volumes/redis/data:/data
