languageCode = "en"
languageName = "English"
weight = 1
title = "Turbine"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/logo-transparent.png"
  secondaryLogo = "images/logo-transparent-dark.png"
  description = "Turbine is a data pipeline for LLM apps. In this blog we will learn how to use Turbine to build LLM apps. We will also explore general topics about LLMs and RAG."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Sumit Ghosh"
  image = "images/turbine-color.png"
  headline = "Learn to harness the power of LLMs and RAG"
  bio = "Turbine is a data pipeline for LLM apps. In this blog we will learn how to use Turbine to build LLM apps. We will also explore general topics about LLMs and RAG."
  links = [
    { email = "mailto:sumit@useturbine.com" },
    { discord = "https://discord.gg/2Vtgedg8S" },
    { twitter = "https://twitter.com/useturbine" },
  ]
