"""Add User.internal column

Revision ID: a1e50eb56d0e
Revises: fc6c8ad592ba
Create Date: 2023-10-27 18:54:59.691079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a1e50eb56d0e"
down_revision: Union[str, None] = "fc6c8ad592ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("internal", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "internal")
    # ### end Alembic commands ###
