"""Create separate Index table

Revision ID: 906d2f3c352d
Revises: a1e50eb56d0e
Create Date: 2023-10-31 14:06:49.172581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '906d2f3c352d'
down_revision: Union[str, None] = 'a1e50eb56d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vector_database', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pipelines', sa.Column('index_id', sa.Uuid(), nullable=True))
    op.drop_constraint('pipelines_user_id_fkey', 'pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'pipelines', 'indexes', ['index_id'], ['id'])
    op.drop_column('pipelines', 'embedding_model')
    op.drop_column('pipelines', 'vector_database')
    op.drop_column('pipelines', 'user_id')
    op.drop_column('pipelines', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pipelines', sa.Column('vector_database', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('pipelines', sa.Column('embedding_model', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.create_foreign_key('pipelines_user_id_fkey', 'pipelines', 'users', ['user_id'], ['id'])
    op.drop_column('pipelines', 'index_id')
    op.drop_table('indexes')
    # ### end Alembic commands ###
